# docker-compose.yml
# Version of the docker-compose file format. '3.8' is a recent, stable version.
version: '3.8'

# This is the main section where we define all the services (containers) we want to run.
services:

  # Service 1: Zookeeper - The Coordinator for Kafka
  # Kafka needs Zookeeper to manage its cluster state, like which brokers are alive.
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Service 2: Kafka - The Data Bus
  # This is the central pipeline where all our logs will flow.
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper # This tells Docker to start Zookeeper *before* starting Kafka.
    ports:
      # We expose port 9092 to our Mac so our Python scripts can connect to Kafka.
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # Service 3: Elasticsearch - The Database for our Alerts
  # This is where we will store the security alerts generated by our detection engine.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node" # We're running it as a single node, not a cluster.
      - "xpack.security.enabled=false" # Disabling security for local development ease.
    ports:
      - "9200:9200" # Exposing the database port to our Mac.

  # Service 4: Kibana - The Dashboard
  # This is the web interface we will use to visualize our alerts.
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.1
    container_name: kibana
    depends_on:
      - elasticsearch # Kibana needs Elasticsearch to be running first.
    ports:
      - "5601:5601" # Exposing the web interface port to our Mac.
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200' # Telling Kibana where to find Elasticsearch.
